### ISSUE TITLE
process.cwd is not a function when running example 

### ISSUE THREAD

**Issue by kubenstein** [rexxars/react-markdown#189]
Hello,
Im trying to run the example, but Im getting the error from vfile lib. The example looks pretty straight forward so I didn't expect any issues. I wonder what I may possibly do incorrect because running `process.cwd()` ([core.js:47](https://github.com/vfile/vfile/blob/2.3.0/core.js#L47)) in browser sounds a bit unnatural.

```
TypeError: Object(...).cwd is not a function
    at new VFile (core.js:47)
    at VFile (core.js:41)
    at Function.parse (index.js:269)
    at ReactMarkdown (react-markdown.js:31)
    at ProxyFacade (react-hot-loader.development.js:617)
    at mountIndeterminateComponent (react-dom.development.js:8574)
    at beginWork (react-dom.development.js:8978)
    at performUnitOfWork (react-dom.development.js:11814)
    at workLoop (react-dom.development.js:11843)
    at renderRoot (react-dom.development.js:11874)
```

appreciate all hints and help,
cheers

**Comment by anicholson** [comment]
I'm seeing this too, with versions: `react-markdown`@ `3.2.2`, `unified` @ `6.2.0` and `vfile` @ `2.3.0`

**Comment by anicholson** [comment]
I'm guessing it's caused by this: https://github.com/vfile/vfile/pull/28

**Comment by anicholson** [comment]
@kubenstein I solved this issue by asking Webpack to [mock `process`](https://webpack.js.org/configuration/node/) for me.

**Comment by kubenstein** [comment]
@anicholson thank you for the input, I solved it too. In my case I was using `webpack.DefinePlugin` to pass env to a node. `vfile`'s `process` was replaced by hash with envs that doesn't contain `cwd` function - thats why I got error `Object(...).cwd is not a function`. Initially I added noop `cwd`, but broke some Uglify functionalities. So my final solution is to look for whole `'process.env'`.

```js
// BAD (initial issue)
new webpack.DefinePlugin({
  process: {
    env: {
      APP_ENV: '...',
    },
  },
})


// BAD (solves the issue but breaks other things)
new webpack.DefinePlugin({
  process: {
    cwd: () => {},
    env: {
      APP_ENV: '...',
    },
  },
})


// GOOD
new webpack.DefinePlugin({
  'process.env': {
    APP_ENV: '...',
  },
})
```

**Comment by alex20465** [comment]
Always dumping the symptoms... what has `vfile`,  `path` and `process` to do with a REACT markdown renderer,

**Comment by cupofjoakim** [comment]
For anyone stumbling in here now: We ran in to this issue on v4.3.1 when we upgraded webpack to v5.9 from v4.x. 

By upgrading from 4.3.1 to 5.0.3 our issues went away.

**Comment by mattyfresh** [comment]
Another option I just happened to stumble upon if anyone is stuck, you can use the  ProvidePlugin available using webpack 5:

```
new webpack.ProvidePlugin({
   process: 'process/browser',
})
```
Essentially, afaik, manually adds the `process` polyfill that is not included with webpack anymore.

**Comment by wooorm** [comment]
Or, you know, you can update `react-markdown`?

**Comment by usmanindustryis** [comment]
I am facing the same issue with:
Because behind the scene `stream-chat-react` is using the 
`react-markdown`

```
    "stream-chat": "^7.1.0",
    "stream-chat-react": "^10.2.0",
```

**Comment by ChristianMurphy** [comment]
@usmanindustryis the answer remains the same (https://github.com/remarkjs/react-markdown/issues/189#issuecomment-790481432).
Make sure `stream-chat-react` is using latest `react-markdown`, and make sure you are using latest `stream-chat-react`.

If you are unable to do so, you can configure webpack to resolve the issue on older versions.
See https://github.com/remarkjs/react-markdown/issues/189#issuecomment-403713084, https://github.com/remarkjs/react-markdown/issues/189#issuecomment-403724135, and https://github.com/remarkjs/react-markdown/issues/189#issuecomment-790469744

Locking this issue, as the issue itself is resolved and remains resolved.
If folks have questions, the Q&A forum is open https://github.com/remarkjs/remark/discussions
